#!/usr/bin/env python3
"""Generate udev rules for plugged-in miniDSP UMIK-2 microphones.

Why: ALSA `hw:N` indices are not stable across reboots. udev binds a stable
ATTR{id} per mic so the card name is reproducible regardless of USB enumeration
order.

UMIK-2 units report a fixed USB serial (`00000`), so serial-based rules collide
when more than one is connected. When serials are NOT unique, we fall back to
naming by **physical USB port path** (e.g. port `3-1.4.1` → `umik_3_1_4_1`),
which is stable as long as the mic stays in the same hub port. When serials are
unique (rare for UMIK-2), we key on serial as before.

Usage:
  python scripts/generate_udev.py            # prints rules to stdout

Install:
  python scripts/generate_udev.py | sudo tee /etc/udev/rules.d/99-umik2.rules
  sudo udevadm control --reload && sudo udevadm trigger
"""

import sys
from pathlib import Path

UMIK_VID = "2752"  # miniDSP


class Mic:
    def __init__(self, port: str, vid: str, pid: str, serial: str, product: str):
        self.port = port  # USB port path / KERNELS, e.g. "3-1.4.1"
        self.vid = vid
        self.pid = pid
        self.serial = serial
        self.product = product


def _alsa_id_from_port(port: str) -> str:
    """ALSA card id: ≤15 chars, [A-Za-z0-9_], starts with a letter.
    "3-1.4.1" → "umik_3_1_4_1"."""
    sanitized = port.replace("-", "_").replace(".", "_")
    cid = f"umik_{sanitized}"
    return cid[:15]


def main() -> int:
    sys_usb = Path("/sys/bus/usb/devices/")
    if not sys_usb.exists():
        print("# /sys/bus/usb/devices not present (Linux only)", file=sys.stderr)
        return 1

    mics: list[Mic] = []
    for dev in sorted(sys_usb.iterdir()):
        vid_file = dev / "idVendor"
        if not vid_file.exists():
            continue
        try:
            if vid_file.read_text().strip() != UMIK_VID:
                continue
            pid = (dev / "idProduct").read_text().strip()
            serial = (dev / "serial").read_text().strip()
            product = (dev / "product").read_text().strip()
        except OSError:
            continue
        mics.append(Mic(dev.name, UMIK_VID, pid, serial, product))

    if not mics:
        print(f"# No miniDSP devices (vendor {UMIK_VID}) currently plugged in.", file=sys.stderr)
        print("# Plug your UMIK-2s and re-run.", file=sys.stderr)
        return 1

    serials = [m.serial for m in mics]
    serials_unique = len(set(serials)) == len(serials) and all(s and s != "00000" for s in serials)

    print(f"# UMIK-2 udev rules — {len(mics)} device(s) found")
    print("# Generated by scripts/generate_udev.py")
    if serials_unique:
        print("# Naming by USB serial (serials are unique).")
    else:
        print("# Naming by USB PORT PATH — UMIK-2 serials are not unique (all report 00000).")
        print("# Each rule pins one physical hub port to a stable ALSA card id.")
        print("# Re-run + reinstall if you move mics to different ports.")
    print()

    for m in mics:
        if serials_unique:
            cid = f"umik2_{m.serial}"
            print(f"# {m.product} · serial {m.serial} → {cid}")
            print(
                f'SUBSYSTEM=="sound", ATTRS{{idVendor}}=="{m.vid}", '
                f'ATTRS{{idProduct}}=="{m.pid}", ATTRS{{serial}}=="{m.serial}", '
                f'ATTR{{id}}="{cid}"'
            )
        else:
            cid = _alsa_id_from_port(m.port)
            print(f"# {m.product} · USB port {m.port} → {cid}")
            print(
                f'SUBSYSTEM=="sound", KERNELS=="{m.port}", '
                f'ATTRS{{idVendor}}=="{m.vid}", ATTRS{{idProduct}}=="{m.pid}", '
                f'ATTR{{id}}="{cid}"'
            )
        print()

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
