#!/usr/bin/env python3
"""Generate udev rules for plugged-in miniDSP UMIK-2 microphones.

Why: ALSA `hw:N` indices are not stable across reboots — udev binds a stable
ATTR{id} per USB serial so the server can reference mics by name regardless of
USB enumeration order.

Usage:
  python scripts/generate_udev.py
    → prints rules to stdout (one per plugged UMIK-2)

Install:
  sudo python scripts/generate_udev.py | sudo tee /etc/udev/rules.d/99-umik2.rules
  sudo udevadm control --reload && sudo udevadm trigger
"""

import sys
from pathlib import Path

UMIK_VID = "2752"  # miniDSP


def main() -> int:
    sys_usb = Path("/sys/bus/usb/devices/")
    if not sys_usb.exists():
        print("# /sys/bus/usb/devices not present (Linux only)", file=sys.stderr)
        return 1

    found: list[tuple[str, str, str, str]] = []
    for dev in sorted(sys_usb.iterdir()):
        vid_file = dev / "idVendor"
        if not vid_file.exists():
            continue
        try:
            vid = vid_file.read_text().strip()
        except OSError:
            continue
        if vid != UMIK_VID:
            continue
        try:
            pid = (dev / "idProduct").read_text().strip()
            serial = (dev / "serial").read_text().strip()
            product = (dev / "product").read_text().strip()
        except OSError:
            continue
        found.append((vid, pid, serial, product))

    if not found:
        print(f"# No miniDSP devices (vendor {UMIK_VID}) currently plugged in.", file=sys.stderr)
        print("# Plug your UMIK-2s and re-run.", file=sys.stderr)
        return 1

    print(f"# UMIK-2 udev rules — {len(found)} device(s) found")
    print("# Generated by scripts/generate_udev.py")
    print()
    for vid, pid, serial, product in found:
        sym = f"umik2_{serial}"
        print(f"# {product} · serial {serial} → ALSA card name {sym}")
        print(
            f'SUBSYSTEM=="sound", ATTRS{{idVendor}}=="{vid}", '
            f'ATTRS{{idProduct}}=="{pid}", ATTRS{{serial}}=="{serial}", '
            f'ATTR{{id}}="{sym}"'
        )
        print()

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
